### ISSUE TITLE
From Source Installation Problem (npm install -g graco)

### ISSUE THREAD

**Issue by ysrikar-UM** [cognitive-engineering-lab/mdbook-quiz#17] opened 2023-02-14 02:26 UTC
I am unable to install graco using npm. [After](url) running the (sudo) npm install -g graco command, I am getting the errors below.
![npm_graco_install_error](https://user-images.githubusercontent.com/105007778/218623066-bdca6532-17a6-441e-8958-40f40836aa60.PNG)

**Comment by willcrichton** [comment] 2023-02-14 02:52
Hi, sorry for the issue, I am encountering this as well. I will get it fixed by tonight.

**Comment by willcrichton** [comment] 2023-02-14 02:57
Also note that if you ever have trouble installing from source, you can use one of the binaries provided in each release.

**Comment by willcrichton** [comment] 2023-02-14 04:27
@ysrikar-UM can you try again and see if the issue is fixed?

**Comment by ysrikar-UM** [comment] 2023-02-14 17:42
Hello, 
Thank you for the quick response. I tried running sudo npm install -g graco again but I still got the same error.

**Comment by willcrichton** [comment] 2023-02-14 17:57
Can you provide the full logs, and details on the platform/OS you're using?

**Comment by ysrikar-UM** [comment] 2023-02-14 21:52
Yes,
I am using Windows 10 and WSL2. I pasted some the log details below. 
27586 verbose notsup Required: {"node":">=12"}
27586 verbose notsup Actual:   {"npm":"6.14.4","node":"10.19.0"}
27587 warn notsup Unsupported engine for cliui@8.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
27588 warn notsup Not compatible with your version of node/npm: cliui@8.0.1
27589 verbose notsup Not compatible with your version of node/npm: cliui@8.0.1
27589 verbose notsup Required: {"node":">=12"}
27589 verbose notsup Actual:   {"npm":"6.14.4","node":"10.19.0"}
27590 warn notsup Unsupported engine for globby@13.1.3: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
27591 warn notsup Not compatible with your version of node/npm: globby@13.1.3
27592 verbose notsup Not compatible with your version of node/npm: globby@13.1.3
27592 verbose notsup Required: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"}
27592 verbose notsup Actual:   {"npm":"6.14.4","node":"10.19.0"}
27593 warn notsup Unsupported engine for detect-newline@4.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
27594 warn notsup Not compatible with your version of node/npm: detect-newline@4.0.0
27595 verbose notsup Not compatible with your version of node/npm: detect-newline@4.0.0
27595 verbose notsup Required: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"}
27595 verbose notsup Actual:   {"npm":"6.14.4","node":"10.19.0"}
27596 warn notsup Unsupported engine for detect-indent@7.0.1: wanted: {"node":">=12.20"} (current: {"node":"10.19.0","npm":"6.14.4"})
27597 warn notsup Not compatible with your version of node/npm: detect-indent@7.0.1
27598 verbose notsup Not compatible with your version of node/npm: detect-indent@7.0.1
27598 verbose notsup Required: {"node":">=12.20"}
27598 verbose notsup Actual:   {"npm":"6.14.4","node":"10.19.0"}
27599 warn notsup Unsupported engine for is-plain-obj@4.1.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
27600 warn notsup Not compatible with your version of node/npm: is-plain-obj@4.1.0
27601 verbose notsup Required: {"node":">=12"}
27601 verbose notsup Actual:   {"npm":"6.14.4","node":"10.19.0"}
27602 warn notsup Unsupported engine for slash@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
27603 warn notsup Not compatible with your version of node/npm: slash@4.0.0
27604 verbose notsup Not compatible with your version of node/npm: slash@4.0.0
27604 verbose notsup Required: {"node":">=12"}
27604 verbose notsup Actual:   {"npm":"6.14.4","node":"10.19.0"}
27605 verbose stack Error: node-pty@0.10.1 install: `node scripts/install.js`
27605 verbose stack Exit status 1
27605 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
27605 verbose stack     at EventEmitter.emit (events.js:198:13)
27605 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
27605 verbose stack     at ChildProcess.emit (events.js:198:13)
27605 verbose stack     at maybeClose (internal/child_process.js:982:16)
27605 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
27606 verbose pkgid node-pty@0.10.1
27607 verbose cwd /mnt/c/Users/syend/Desktop/Everything/FPLab2/test_quiz
27608 verbose Linux 5.15.79.1-microsoft-standard-WSL2
27609 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "graco"
27610 verbose node v10.19.0
27611 verbose npm  v6.14.4
27612 error code ELIFECYCLE
27613 error errno 1
27614 error node-pty@0.10.1 install: `node scripts/install.js`
27614 error Exit status 1
27615 error Failed at the node-pty@0.10.1 install script.
27615 error This is probably not a problem with npm. There is likely additional logging output above.
27616 verbose exit [ 1, true ]

**Comment by ysrikar-UM** [comment] 2023-02-27 17:46
Yes, this worked. Thank you, I was successfully able to install graco.

**Comment by willcrichton** [comment] 2023-09-18 20:30
This issue has been made moot since the switch to Depot.

**Closed by willcrichton** 2023-09-18 20:30 UTC
